const data = [
    {
      "gameId": 13,
      "name": "Catan",
      "image": "https://cf.geekdo-images.com/original/img/A-0yDJkve0avEicYQ4HoNO-HkK8=/0x0/pic2419375.jpg",
      "thumbnail": "https://cf.geekdo-images.com/thumb/img/g8LvJsd2oLAub6AEKN_Xpdoi8Sw=/fit-in/200x150/pic2419375.jpg",
      "minPlayers": 3,
      "maxPlayers": 4,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 1995,
      "bggRating": 0.0,
      "averageRating": 7.22989,
      "rank": 278,
      "numPlays": 2,
      "rating": 7.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
  },
    {
      "gameId": 62871,
      "name": "Zombie Dice",
      "image": "https://cf.geekdo-images.com/original/img/9qhoilvjJEdn_djjqSMAYT03qno=/0x0/pic2664015.jpg",
      "thumbnail": "https://cf.geekdo-images.com/thumb/img/G-PC-kqCrC-kPqrDZyEG32mkfvM=/fit-in/200x150/pic2664015.jpg",
      "minPlayers": 2,
      "maxPlayers": 99,
      "playingTime": 20,
      "isExpansion": false,
      "yearPublished": 2010,
      "bggRating": 0.0,
      "averageRating": 6.23033,
      "rank": 1704,
      "numPlays": 13,
      "rating": 6.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
  },
  {
    "gameId": 68448,
    "name": "7 Wonders",
    "image": "https://cf.geekdo-images.com/original/img/3DP_RW5lTX0WrV67s8qi8CsiXoQ=/0x0/pic860217.jpg",
    "thumbnail": "https://cf.geekdo-images.com/thumb/img/Grz-qM9xwxlvQGK7B-MiljtO9pQ=/fit-in/200x150/pic860217.jpg",
    "minPlayers": 2,
    "maxPlayers": 7,
    "playingTime": 30,
    "isExpansion": false,
    "yearPublished": 2010,
    "bggRating": 0.0,
    "averageRating": 7.8079,
    "rank": 40,
    "numPlays": 23,
    "rating": 9.0,
    "owned": true,
    "preOrdered": false,
    "forTrade": false,
    "previousOwned": false,
    "want": false,
    "wantToPlay": false,
    "wantToBuy": false,
    "wishList": false,
    "userComment": ""
},
{
    "gameId": 128882,
    "name": "The Resistance: Avalon",
    "image": "https://cf.geekdo-images.com/original/img/kFDTpCfe476T1bzZUtNAbGyIjNg=/0x0/pic1398895.jpg",
    "thumbnail": "https://cf.geekdo-images.com/thumb/img/rSivtcma94IGqMyHgzgfhjcyYDs=/fit-in/200x150/pic1398895.jpg",
    "minPlayers": 5,
    "maxPlayers": 10,
    "playingTime": 30,
    "isExpansion": false,
    "yearPublished": 2012,
    "bggRating": 0.0,
    "averageRating": 7.6719,
    "rank": 84,
    "numPlays": 0,
    "rating": -1.0,
    "owned": false,
    "preOrdered": false,
    "forTrade": false,
    "previousOwned": true,
    "want": false,
    "wantToPlay": false,
    "wantToBuy": false,
    "wishList": false,
    "userComment": ""
  }
]
export default data;